
@host = http://localhost:8080
POST{{host}}/api/devices
Content-Type: application/json
Accept: application/json

{
  "deviceName": "Device 2",
  "partNumber": "PN-102",
  "buildingName": "TRIL4",
  "deviceType": "CISCO 420",
  "numberOfShelfPositions": 7
}


GET {{host}}/api/devices
Content-Type: application/json
"Accept": application/json

