
@host = http://localhost:8080
POST{{host}}/api/v1/devices
Content-Type: application/json
Accept: application/json

{
  "deviceName": "NYC-Core-R1",
  "deviceType": "8180 Coherent Aggregation Router",
  "partNumber": "170-8180-900",
  "buildingName": "New York City POP",
  "numberOfShelfPositions": 4
}
