spring.application.name=NetworkDevices

# Server
server.port=8080
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# Neo4j Java Driver auto-config (no Spring Data)
neo4j.uri=neo4j://127.0.0.1:7687
neo4j.authentication.username=neo4j
neo4j.authentication.password=@Pi4dAssignment

neo4j.database=neo4j


logging.level.org.springframework.web=INFO
logging.level.org.neo4j.driver=INFO

